---
title: ""
toc: false
page-layout: full
link-external-newwindow: true
---

## BMSC 620: Introduction to Biostatistics

### Winter 2027

Welcome to **BMSC 620: Introduction to Biostatistics.** This course introduces fundamental statistical methods commonly used in the biomedical and health sciences, with an emphasis on understanding, interpretation, and clear communication rather than mathematical derivations.

We will begin with descriptive statistics and graphical methods for summarizing data, followed by an introduction to basic probability concepts that motivate statistical inference. Key probability and sampling distributions, including the binomial, Poisson, and normal distributions, will be introduced as tools for understanding variability and uncertainty in data.

The course will then cover confidence intervals and hypothesis testing for one- and two-sample problems, using both parametric and nonparametric approaches. Additional topics include inference for proportions, analysis of two-way tables, one-way analysis of variance (ANOVA), correlation, and simple linear regression.

Throughout the course, emphasis will be placed on selecting appropriate statistical methods, interpreting results, and communicating conclusions in a way that is accessible to audiences without formal statistical training. Students will gain hands-on experience using statistical software (R) for basic data management, visualization, and interpretation of output generated by statistical analyses, as well as for building reproducible analytical workflows.

*Course materials and structure for BMSC 620 were developed by Emile Latour and informed by prior offerings taught by Meike Niederhausen and Nicky Wakim. Portions of the syllabus, resources, and instructional approach were adapted from their courses, with permission, and modified for this offering.*

::: grid
::: g-col-3
### Instructor

{{< iconify fluent person-24-filled size=24px >}} [Emile Latour, MS](instructors.qmd)

<!-- {{< iconify bi building-fill size=24px >}} RJH 4320 -->
{{< iconify bi building-fill size=24px >}} KCRB

{{< iconify tabler mail-filled size=24px >}} [latour\@ohsu.edu](mailto:latour@ohsu.edu)
:::

::: g-col-3
### Office hours

[Emile](https://ohsu.webex.com/meet/latour)
{{< iconify icon-park-solid time size=24px >}} Thursday, 1:00–2:00 PM

[Joseph](https://ohsu.webex.com/meet/hwangjo)
{{< iconify icon-park-solid time size=24px >}} Friday, 10:00-11:00 AM

[Nick](https://ohsu.webex.com/meet/chaiyach)
{{< iconify icon-park-solid time size=24px >}} Wednesday, 1:00–2:00 PM


:::

::: g-col-3
### Course details

{{< iconify fa6-solid calendar-days size=24px >}} Mondays, Wednesdays

{{< iconify fa6-solid calendar size=24px >}} January 5–March 20

{{< iconify icon-park-solid time size=24px >}} 9:00 AM–10:30 AM

{{< iconify fa6-solid person-chalkboard size=24px >}} In-person, RJH 4320

**Note:** Class will meet in **MAC 3198** on **January 21** only.

:::

::: g-col-3
### Contact

E-mail is the best way to get in contact with me. I will try to respond to all course-related e-mails within 24 hours Monday-Friday.
:::
:::

---

::: grid
::: g-col-9
:::

::: g-col-3
[{{< iconify icomoon-free github size=24px >}} View the source on GitHub](https://github.com/emilelatour/BMSC_620_W26){.github-link}
:::
:::